name: Build (macOS)

on:
    push:
        paths-ignore:
            - "README.md"
            - "LICENSE"
            - "@types"
            - ".gitignore"
            - ".prettierrc.json"
            - ".vscode"
            - "tsconfig.json"

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm i

            - name: Build
              run: npm run build:mac