name: Build (macOS)

on:
    workflow_dispatch:
    push:
        paths:
            - ".github/workflows/build-mac.yml"
            - "src/**"
            - "package.json"

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Create i18n types
              run: npm run generate:i18n-types-ci

            - name: Build
              run: npm run build:macos
              env:
                  GH_TOKEN: ${{ secrets.github_token }}
                  ELECTRON: true
                  USE_HARD_LINKS: false
